[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
FastSphericalHarmonics = "d335c211-7587-445e-a753-f0b1fb7e445f"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
MIRTjim = "170b2178-6dee-4cb0-8729-b3e8b57834cc"
MRIBase = "f7771a9a-6e57-4e71-863b-6e4b6a2f17df"
MRICoilSensitivities = "c57eb701-aafc-44a2-a53c-128049758959"
MRIFieldmaps = "5af58b90-8a55-4daf-adb4-2008a66a38cf"
MRIFiles = "5a6f062f-bf45-497d-b654-ad17aae2a530"
MRIOperators = "fb1137e3-90a6-46ce-a672-6e1e53d120f2"
MRIReco = "bdf86e05-2d2b-5731-a332-f3fe1f9e047f"
MRISampling = "9be66c26-f988-4649-80fc-f4721a4a33f2"
MRISimulation = "8988da37-ea20-4fa6-9af7-8a6f6f9a8970"
MriResearchTools = "557dad86-b9bd-4533-8525-1a39684d020f"
NFFT = "efe261a4-0d2b-5849-be55-fc731d526b0d"
NFFTTools = "7424e34d-94f7-41d6-98a0-85abaf1b6c91"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ROMEO = "1ea8258b-a15d-4adb-ad20-01632f467a84"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SphericalHarmonicExpansions = "504afa71-bae7-47b4-8ec9-3851161806ac"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"
